### ISSUE TITLE
Roadmap for 0.1.0

### ISSUE THREAD

**Issue by nugmanoff** [y-crdt/yswift#2]
Following up on conversation with @heckj

Here is the rough roadmap for 0.1.0:
* [x] Document
* [x] Transaction
* [x] Text
  * [x] Embeds
  * [x] Attributes
* [x] Array
* [x] Map
* [x] Observations
* [x] Swift wrapper
  * [x] Thread-safety
  * [x] Idiomatic API (Conformance to native protocols, "Swifty" feel & etc)
* [x] Examples
* [x] Basic docs for library consumers

As of now we will probably be leaving XML types, Undo/Redo Manager, Awareness protocol & other stuff to 0.2.0 due to their _complementary_ nature.

**Comment by heckj** [comment]
Question on the flow here - any preference for having me work in my local fork and send pull requests vs. working in the repository directly? Right now I don't think I have permissions on the repo to do anything, but I'm happy to drop in pull requests and add you as a reviewer for work I do. That work OK for you? (If you want me to self-merge at any point, we'll just need to give/get me permissions into the repo)

**Comment by nugmanoff** [comment]
Both ways work for me. But I think we need to get you maintainer permissions, need to ask @dmonad for that. I think we can voluntarily ask for review on big changes from each other, but not block each other on small changes. Common sense applies – when we will like we need review, we ask for it :) Either way – I believe PRs are the way to go now once there are 2 of us.

**Comment by dmonad** [comment]
Now both of you have maintainer access ;)

You can organize the work however you want. Make sure to optimize it over time. I also believe that it makes sense to open a PR for all changes - just for visibility (for each other, and for outsiders). 

You seem to already agree on using "common sense" on whether to ask for a review :) Just make sure that you give each other a chance to see more significant changes.

**Comment by nugmanoff** [comment]
[0.1.0 release](https://github.com/y-crdt/yswift/releases/tag/0.1.0) is out 🥳
